import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import express from 'express';
import { once } from 'node:events';
import { FirebaseRtdb as DB } from './firebaseRtdb';
import * as M from './marketplace';
import { atomicDocument } from './atomicStore';
import { seal,unseal } from './privateData';
import { marketplaceRouter } from './marketplaceRoutes';
import { gatewayHash,verifyKycWebhook,createSubmerchant } from './easebuzzMarketplace';
import { settleSale,requestRefund,reconcileRefund } from './marketplaceFinance';
import { SELLER_AGREEMENT_VERSION } from '../src/config/marketplace';
function setup(t:any){
 const before={...process.env};Object.assign(process.env,{NODE_ENV:'test',DATABASE_PROVIDER:'local',MARKETPLACE_ENCRYPTION_KEY:Buffer.alloc(32,5).toString('base64'),MARKETPLACE_LEGAL_NAME:'Synthetic Operator',MARKETPLACE_COMMISSION_BPS:'1000',EASEBUZZ_MARKETPLACE_APPROVED:'true',EASEBUZZ_ONDEMAND_APPROVED:'true',EASEBUZZ_PLATFORM_SPLIT_LABEL:'platform',EASEBUZZ_KEY:'synthetic',EASEBUZZ_SALT:'synthetic-salt',EASEBUZZ_ENV:'test',EASEBUZZ_MERCHANT_EMAIL:'merchant@example.test'});
 t.after(()=>{for(const key of Object.keys(process.env))if(!(key in before))delete process.env[key];Object.assign(process.env,before);});
 const memory:Record<string,any>={};
 t.mock.method(DB,'get',async(path:string)=>{if(path==='marketplace_sellers')return Object.fromEntries(Object.entries(memory).filter(([k])=>k.startsWith(path+'/')).map(([k,v])=>[k.split('/')[1],structuredClone(v)]));return structuredClone(memory[path]??null);});
 t.mock.method(DB,'set',async(path:string,value:any)=>{memory[path]=structuredClone(value);return value;});return memory;
}
const registration={legalName:'Synthetic Seller',storeName:'Synthetic Studio',phone:'9876543210',address:'123 Synthetic Street, India',pan:'ABCDE1234F',gstin:'',holder:'Synthetic Seller',account:'123456789012',ifsc:'ABCD0123456',bank:'Synthetic Bank',branch:'Synthetic Branch',plan:'starter',signedName:'Synthetic Seller',agreementVersion:SELLER_AGREEMENT_VERSION,commissionBps:1000,acceptAgreement:true,ownsRights:true,adult:true};
const product={title:'Original website template',description:'A complete original template with documented components and clear usage instructions for buyers.',price:100,category:'Website templates',image:'https://images.example.test/cover.png',previewUrl:'https://preview.example.test',version:'1.0',fileSize:'1 MB',license:'Use for one commercial website; redistribution is prohibited.',requirements:'HTML and CSS',whatsIncluded:'HTML files\nCSS styles',support:'Contact support@example.test for product help.',sourceUrl:'https://mega.nz/file/abcdefgh#syntheticprivatekey123456789',ownsRights:true};
async function ready(t:any){const mem=setup(t);await M.registerSeller('seller1','seller@example.test',registration,'127.0.0.1');await M.submitProduct('seller1',product);const s=mem['marketplace_sellers/seller1'];s.status='approved';s.kycStatus='approved';s.providerId='S_SYNTH';s.splitLabel='vendor';s.approvalReference='approved-reference';Object.values(s.products).forEach((p:any)=>p.status='active');return mem;}
test('registration records exact agreement and encrypts identity; invalid consent and duplicate registrations fail',async t=>{const mem=setup(t);await assert.rejects(M.registerSeller('seller1','seller@example.test',{...registration,acceptAgreement:false},'127.0.0.1'));const s=await M.registerSeller('seller1','seller@example.test',registration,'127.0.0.1');assert.equal(s.status,'pending');assert.equal(s.kycStatus,'pending');assert.equal(s.agreement.sha256,crypto.createHash('sha256').update(s.agreement.text).digest('hex'));assert.ok(!JSON.stringify(s).includes(registration.pan));assert.equal(unseal<any>(s.privateData,'seller:seller1').pan,registration.pan);assert.throws(()=>unseal(s.privateData,'seller:other'));assert.equal('privateData' in M.sellerView(s),false);await assert.rejects(M.registerSeller('seller1','seller@example.test',registration,'127.0.0.1'));assert.equal(Object.keys(mem).length,1);});
test('private source never appears in public catalog; approval and suspension control visibility',async t=>{const mem=await ready(t);const products=await M.publicMarketplaceProducts();assert.equal(products.length,1);assert.ok(!JSON.stringify(products).includes('encryptedSource'));assert.ok(!JSON.stringify(products).includes('syntheticprivatekey'));assert.ok((await M.sellerSource(products[0].id)).includes('syntheticprivatekey'));mem['marketplace_sellers/seller1'].status='suspended';assert.equal((await M.publicMarketplaceProducts()).length,0);});
test('source validation rejects local hosts, credentials, non-HTTPS and unapproved domains',t=>{setup(t);for(const u of ['http://mega.nz/file/a#123456789123','https://127.0.0.1/x.zip','https://mega.nz.evil.example/x.zip','https://user:pass@mega.nz/file/a#123456789123','https://mega.nz:8443/file/a#123456789123','https://mega.nz/folder/a#123456789123'])assert.throws(()=>M.validateSource(u));});
test('checkout prevents mixed sellers, discounts, wrong gateway and held/unapproved sellers',async t=>{const mem=await ready(t),p=(await M.publicMarketplaceProducts())[0],items=[{product:p}];assert.equal((await M.prepareMarketplaceOrder(items,'easebuzz',null))?.sellerId,'seller1');await assert.rejects(M.prepareMarketplaceOrder([...items,{product:{id:'store'}}],'easebuzz',null));await assert.rejects(M.prepareMarketplaceOrder(items,'payu',null));await assert.rejects(M.prepareMarketplaceOrder(items,'easebuzz','SAVE10'));mem['marketplace_sellers/seller1'].hold={reason:'review'};await assert.rejects(M.prepareMarketplaceOrder(items,'easebuzz',null));});
test('concurrent verified delivery accrues one sale; unverified environment cannot accrue',async t=>{const mem=await ready(t);const order={id:'order1',marketplace:{sellerId:'seller1',commissionBps:1000},paymentProvider:'Easebuzz',paymentStatus:'PAID',paymentEnvironment:'live',total:100,transactionId:'payment1',easebuzzTxnId:'txn1'};await assert.rejects(M.accrueSale({...order,paymentEnvironment:'test'}));await Promise.all(Array.from({length:20},()=>M.accrueSale(order)));const s=mem['marketplace_sellers/seller1'];assert.equal(Object.keys(s.ledger).length,1);assert.equal(s.ledger.order1.sellerPaise,9000);assert.equal(s.events.filter((e:any)=>e.event==='SALE_VERIFIED').length,1);});
test('official submerchant request hashes required identity fields; webhook signature must match',async t=>{setup(t);let body:any;t.mock.method(globalThis,'fetch',async(url:any,init:any)=>{assert.equal(String(url),'https://testdashboard.easebuzz.in/merchant/v1/submerchant/create/');body=JSON.parse(init.body);return new Response(JSON.stringify({status:true,submerchant_id:'S_SYNTH'}));});await createSubmerchant({legalName:'Seller',email:'seller@example.test',phone:'9876543210'},{holder:'Seller',account:'1234567890',bank:'Bank',branch:'Branch',ifsc:'ABCD0123456'},'long-synthetic-password');assert.equal(body.merchant_details.hash,gatewayHash('synthetic','seller@example.test','9876543210','synthetic-salt'));const data={submerchant_id:'S_SYNTH',hash:gatewayHash('synthetic','S_SYNTH','synthetic-salt')};assert.equal(verifyKycWebhook({data}),true);assert.equal(verifyKycWebhook({data:{...data,submerchant_id:'other'}}),false);});
async function sale(t:any){const mem=await ready(t);await M.accrueSale({id:'order1',marketplace:{sellerId:'seller1',commissionBps:1000},paymentProvider:'Easebuzz',paymentStatus:'PAID',paymentEnvironment:'live',total:100,transactionId:'payment1',easebuzzTxnId:'txn1'});mem['marketplace_sellers/seller1'].ledger.order1.eligibleAt=new Date(Date.now()-1000).toISOString();return mem;}
test('settlement requires exact split and accepted request is not marked settled; retries only query status',async t=>{const mem=await sale(t),calls:string[]=[];t.mock.method(globalThis,'fetch',async(url:any)=>{const path=new URL(url).pathname;calls.push(path);const result=path.includes('post-split/v1/create')?{status:true,request_status:'success',configuration:[{label:'vendor',status:'success'},{label:'platform',status:'success'}]}:path.includes('post-split/v1/retrieve')?{status:'success',split_configuration:[{label:'vendor',amount:90},{label:'platform',amount:10}]}:path.includes('initiate')?{status:true,transactions:[{easebuzz_id:'payment1',status:'accepted'}]}:{status:true,transactions:[{easebuzz_id:'payment1',settlement_status:'success',txn_settlement_amount:98,settlement_info:{settlement_id:'settlement1',utr_number:'synthetic-utr'}}]};return new Response(JSON.stringify(result));});await settleSale('seller1','order1');assert.equal(mem['marketplace_sellers/seller1'].ledger.order1.status,'settlement_pending');await settleSale('seller1','order1');assert.equal(mem['marketplace_sellers/seller1'].ledger.order1.status,'settled');assert.equal(calls.filter(p=>p.includes('/ondemand/initiate')).length,1);});
test('provider timeout creates unknown split and never sends a bank instruction',async t=>{const mem=await sale(t);let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;throw new Error('timeout');});await assert.rejects(settleSale('seller1','order1'));assert.equal(mem['marketplace_sellers/seller1'].ledger.order1.status,'split_unknown');assert.equal(calls,1);});
test('refund initiation is at most once, confirmation reverses seller share and commission',async t=>{const mem=await sale(t);const order:any={id:'order1',marketplace:{sellerId:'seller1'},paymentStatus:'PAID',total:100,transactionId:'payment1',customerEmail:'buyer@example.test',customer:{phone:'9876543210'}};t.mock.method(DB,'getGlobalOrder',async()=>structuredClone(order));t.mock.method(DB,'saveGlobalOrder',async(o:any)=>{Object.assign(order,o);});let calls=0;t.mock.method(globalThis,'fetch',async(url:any)=>{calls++;return new Response(JSON.stringify(String(url).includes('retrieve')?{status:true,easebuzz_id:'payment1',refunds:[{refund_id:'refund1',refund_status:'refunded',refund_amount:50}]}:{status:true,easebuzz_id:'payment1',refund_id:'refund1',refund_amount:50}));});await requestRefund('seller1','order1',5000,'Material product defect','admin');await assert.rejects(requestRefund('seller1','order1',5000,'Duplicate submission','admin'));assert.equal(calls,1);await reconcileRefund('seller1','order1');const row=mem['marketplace_sellers/seller1'].ledger.order1;assert.equal(row.commissionRefundPaise,500);assert.equal(row.sellerRefundPaise,4500);assert.equal(row.status,'adjustment_review');assert.equal(order.refundAmount,50);});
test('marketplace HTTP endpoints require session/admin and private source is absent from seller response',async t=>{await ready(t);const app=express();app.use(express.json());const auth:any=(req:any,res:any,next:any)=>{if(req.headers.authorization!=='synthetic-session')return res.status(401).json({message:'Sign in'});req.userId='seller1';req.userEmail='seller@example.test';next();};const admin:any=(_req:any,res:any)=>res.status(403).json({message:'Admin required'});app.use('/api/marketplace',marketplaceRouter(auth,admin));const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as any).port}/api/marketplace`;assert.equal((await fetch(base+'/seller')).status,401);assert.equal((await fetch(base+'/admin/sellers')).status,403);const result=await(await fetch(base+'/seller',{headers:{authorization:'synthetic-session'}})).json();assert.ok(!JSON.stringify(result).includes('encryptedSource'));assert.ok(!JSON.stringify(result).includes(registration.pan));assert.equal((await fetch(base+'/seller/products',{method:'POST',headers:{authorization:'synthetic-session',origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify(product)})).status,403);});
test('unknown refund reference is verified against provider transaction and amount before linking',async t=>{
 const {linkUnknownRefund}=await import('./marketplaceFinance');const mem=await sale(t);const row=mem['marketplace_sellers/seller1'].ledger.order1;row.status='refund_pending';row.refundRequest={status:'unknown',amountPaise:10000};
 t.mock.method(globalThis,'fetch',async()=>new Response(JSON.stringify({status:true,easebuzz_id:'wrong-payment',refunds:[{refund_id:'refund1',refund_amount:100,refund_status:'queued'}]})));
 await assert.rejects(linkUnknownRefund('seller1','order1','refund1','admin'));assert.equal(row.refundRequest.providerId,undefined);
});
test('chargeback notice restricts the correct sale without debiting an account or allowing duplicate notices',async t=>{
 const {recordChargeback}=await import('./marketplaceFinance');const mem=await sale(t);let saved:any;t.mock.method(DB,'getGlobalOrder',async()=>({id:'order1',marketplace:{sellerId:'seller1'}}));t.mock.method(DB,'saveGlobalOrder',async(order:any)=>{saved=order;});
 await recordChargeback('seller1','order1',10000,'verified-synthetic-reference','Confirmed provider notice','admin');assert.equal(saved.deliveryStatus,'REVOKED');assert.equal(mem['marketplace_sellers/seller1'].ledger.order1.status,'dispute_review');await assert.rejects(recordChargeback('seller1','order1',10000,'duplicate-synthetic-reference','Duplicate notice','admin'));
});
