import React, { useEffect, useState } from 'react';
import { useApp } from '../context/AppContext';
import { BUSINESS } from '../config/business';
import { SELLER_PLANS, SELLER_CATEGORIES } from '../config/marketplace';
export async function marketplaceApi(path:string,body?:unknown) {
 const response=await fetch('/api/marketplace'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 const result=await response.json();if(!response.ok)throw new Error(result.message||'Please try again.');return result;
}
const button='rounded-xl bg-slate-900 px-5 py-3 text-white font-semibold disabled:opacity-50';
const card='rounded-2xl border border-slate-200 bg-white p-6 shadow-sm';
const money=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format((paise||0)/100);
export function Field({name,label,type='text',required=true,textarea=false,defaultValue='',...props}:any) {return <label className="block text-sm font-medium text-slate-700">{label}{textarea?<textarea className="mt-2 w-full rounded-lg border border-slate-300 p-3 min-h-28" name={name} required={required} defaultValue={defaultValue} {...props}/>:<input className="mt-2 w-full rounded-lg border border-slate-300 p-3" name={name} type={type} required={required} defaultValue={defaultValue} {...props}/>}</label>;}
const values=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));
function Agree({name,children}:any){return <label className="flex gap-3 text-sm leading-6"><input name={name} type="checkbox" required className="mt-1 h-4 w-4 shrink-0"/>{children}</label>;}
function Layout({title,children}:any){return <div className="mx-auto max-w-6xl px-5 py-12 space-y-7"><h1 className="text-3xl sm:text-4xl font-bold">{title}</h1>{children}</div>;}
export function MarketplacePage(){
 const {currentPath,currentUser,navigate,isAuthenticated}=useApp();
 const [config,setConfig]=useState<any>(null),[seller,setSeller]=useState<any>(null),[store,setStore]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[tab,setTab]=useState('overview');
 const load=async()=>{setError('');const cfg=await marketplaceApi('/config');setConfig(cfg);if(isAuthenticated){const result=await marketplaceApi('/seller');setSeller(result.seller);}setLoaded(true);};
 useEffect(()=>{let active=true;setLoaded(false);setStore(null);const run=async()=>{try{if(currentPath.startsWith('/sellers/')){const result=await marketplaceApi('/stores/'+encodeURIComponent(currentPath.split('/')[2]));if(active){setStore(result);setLoaded(true);}}else await load();}catch(e){if(active){setError((e as Error).message);setLoaded(true);}}};void run();return()=>{active=false;};},[currentPath,isAuthenticated]);
 const act=async(work:()=>Promise<void>)=>{setError('');setMessage('');setBusy(true);try{await work();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const alert=<>{error&&<p role="alert" className="rounded-xl bg-red-50 text-red-800 p-4">{error}</p>}{message&&<p role="status" className="rounded-xl bg-emerald-50 text-emerald-900 p-4">{message}</p>}</>;
 if(!loaded)return <Layout title="Seller marketplace"><p role="status">Loading…</p></Layout>;
 if(currentPath.startsWith('/sellers/'))return <Layout title={store?.name||'Seller store'}>{alert}<div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{store?.products.map((p:any)=><a key={p.id} className={card} href={'/product/'+p.slug}><img src={p.image} alt="" className="aspect-video rounded-xl object-cover w-full"/><h2 className="font-bold text-xl mt-4">{p.title}</h2><p>{p.shortDescription}</p><p className="mt-3 font-bold">{money(p.price*100)}</p></a>)}</div>{store&&!store.products.length&&<p>This seller has no published products yet.</p>}</Layout>;
 if(currentPath==='/sell')return <Layout title="Make something great. Sell it here.">{alert}<p className="text-lg text-slate-600 max-w-3xl">A marketplace for original templates, code and digital design. Keep your files in your own storage. We help you list, take payments and deliver purchases.</p><div className="grid md:grid-cols-3 gap-5">{SELLER_PLANS.map(p=><article key={p.id} className={card}><h2 className="font-bold text-xl">{p.name}</h2><p className="text-4xl font-bold my-5">₹0 <span className="text-sm font-normal">/ month</span></p><p>{p.description}</p><ul className="text-sm space-y-3 my-6"><li>Seller storefront and dashboard</li><li>Product review before publication</li><li>Order and settlement records</li><li>Your own file storage</li></ul><button className={button} onClick={()=>navigate(isAuthenticated?'/seller':'/register')}>Get started</button></article>)}</div><p>Marketplace commission: {config?.commissionBps/100}% per sale. Processing charges and applicable taxes may apply. No subscription is charged for any plan.</p><div className={card}><h2 className="font-bold text-xl mb-3">From creator to seller</h2><ol className="list-decimal pl-5 space-y-2"><li>Create an account, choose a free plan and accept the seller agreement.</li><li>Complete identity and bank verification using your secure onboarding link.</li><li>Submit your product information and private ZIP link for review.</li><li>After approval, share your store link and track verified sales.</li></ol></div><p><a className="underline" href="/policies/seller-agreement">Seller agreement</a> · <a className="underline" href="/policies/prohibited-products">Allowed and prohibited products</a> · <a className="underline" href="/seller">Seller dashboard</a></p></Layout>;
 if(!isAuthenticated)return <Layout title="Your seller account">{alert}<p>Sign in to register or manage your store.</p><button className={button} onClick={()=>navigate('/login')}>Sign in</button> <button className={button} onClick={()=>navigate('/register')}>Create account</button></Layout>;
 if(!seller)return <Layout title="Register your seller account">{alert}<p>Use your legal details. Your PAN and bank account are private; your store name appears publicly.</p>{!config?.registrationEnabled?<div className={card}><p>Seller applications are opening soon. Contact <a className="underline" href={`mailto:${BUSINESS.email}`}>{BUSINESS.email}</a> for assistance.</p></div>:<form className={card+' space-y-6'} onSubmit={event=>{event.preventDefault();const data=values(event.currentTarget);void act(async()=>{await marketplaceApi('/seller',{...data,commissionBps:config.commissionBps,agreementVersion:config.agreementVersion,acceptAgreement:true,ownsRights:true,adult:true});await load();setMessage('Application received. Complete your verification next.');});}}><div className="grid sm:grid-cols-2 gap-5"><Field name="legalName" label="Full legal name / entity name"/><Field name="storeName" label="Public store name"/><Field name="phone" label="Indian mobile number" pattern="[6-9][0-9]{9}" maxLength={10}/><Field name="address" label="Legal address" minLength={15}/><Field name="pan" label="PAN number" pattern="[A-Z]{5}[0-9]{4}[A-Z]" maxLength={10} autoComplete="off"/><Field name="gstin" label="GSTIN (if applicable)" required={false}/><Field name="holder" label="Bank account holder"/><Field name="account" label="Bank account number" pattern="[0-9]{9,18}" autoComplete="off"/><Field name="ifsc" label="IFSC" pattern="[A-Z]{4}0[A-Z0-9]{6}"/><Field name="bank" label="Bank name"/><Field name="branch" label="Branch name"/><label className="text-sm font-medium">Free plan<select name="plan" className="block w-full mt-2 rounded-lg border p-3">{SELLER_PLANS.map(p=><option value={p.id} key={p.id}>{p.name} — ₹0/month, {p.productLimit} products</option>)}</select></label></div><h2 className="text-xl font-bold">Your agreement</h2><p>Operator: {config.operator}. Commission: {config.commissionBps/100}% per sale. Account email: {currentUser?.email}.</p><div tabIndex={0} className="max-h-96 overflow-y-auto rounded-xl bg-slate-50 border p-5 whitespace-pre-line text-sm leading-7">{config.agreement}</div><Field name="signedName" label="Type your full legal name to accept electronically"/><Agree name="acceptAgreement">I have read and accept the seller agreement, privacy policy and disclosed commission.</Agree><Agree name="ownsRights">I will sell only products I own or have the necessary rights to sell, and will follow the prohibited-products policy.</Agree><Agree name="adult">I am at least 18 and authorized to enter this agreement.</Agree><button className={button} disabled={busy}>{busy?'Submitting…':'Accept agreement & create seller account'}</button></form>}</Layout>;
 const ledger=Object.values(seller.ledger||{}) as any[];
 return <Layout title={seller.storeName}>{alert}<div className="flex flex-wrap gap-3"><span className="rounded-full bg-slate-100 px-4 py-2">Account: {seller.status.replaceAll('_',' ')}</span><span className="rounded-full bg-slate-100 px-4 py-2">Identity: {seller.kycStatus}</span><span className="rounded-full bg-slate-100 px-4 py-2">{seller.plan} · ₹0/month</span></div><p>Store link: <a className="underline break-all" href={'/sellers/'+seller.id}>{window.location.origin}/sellers/{seller.id}</a>{seller.status!=='approved'&&' — available publicly after approval'}</p><nav className="flex flex-wrap gap-2" aria-label="Seller dashboard">{['overview','products','add product','verification','agreement','support'].map(t=><button key={t} className={tab===t?button:'rounded-xl border px-5 py-3 capitalize'} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {seller.hold&&<div role="status" className="rounded-xl border border-amber-300 bg-amber-50 p-5"><h2 className="font-bold">Settlement restricted</h2><p>{seller.hold.reason}</p><p>Review date: {new Date(seller.hold.reviewAt).toLocaleDateString()}. A review date is not a guaranteed release date. Contact support for the recorded payment-partner status.</p></div>}
 {tab==='overview'&&<><div className="grid sm:grid-cols-3 gap-5">{[['Gross sales',ledger.reduce((n,l)=>n+l.grossPaise,0)],['Platform commission',ledger.reduce((n,l)=>n+l.commissionPaise-(l.commissionRefundPaise||0),0)],['Seller proceeds before processing charges',ledger.reduce((n,l)=>n+l.sellerPaise-(l.sellerRefundPaise||0),0)]].map(([label,value])=><div key={String(label)} className={card}><p>{label}</p><p className="font-bold text-2xl mt-3">{money(Number(value))}</p></div>)}</div><div className={card+' overflow-x-auto'}><h2 className="text-xl font-bold mb-4">Sales & settlement activity</h2>{!ledger.length?<p>Your verified sales will appear here.</p>:<table className="w-full text-sm text-left"><thead><tr>{['Order','Gross','Commission','Refund','Expected seller share','Status / settlement reference'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{ledger.map(l=><tr className="border-t" key={l.orderId}><td className="p-3">{l.orderId}</td><td>{money(l.grossPaise)}</td><td>{money(l.commissionPaise-(l.commissionRefundPaise||0))}</td><td>{money(l.refundPaise)}</td><td>{money(l.sellerPaise-(l.sellerRefundPaise||0))}</td><td>{l.status.replaceAll('_',' ')}<br/>{l.settlement?.utr_number}</td></tr>)}</tbody></table>}<p className="text-sm mt-5">Expected shares exclude separately reconciled processing fees and taxes. A pending request is not a bank credit. Settled transactions show the payment partner’s reference.</p></div></>}
 {tab==='products'&&<div className="grid sm:grid-cols-2 gap-5">{seller.products.length?seller.products.map((p:any)=><article className={card} key={p.id}><h2 className="text-xl font-bold">{p.title}</h2><p>{money(p.price*100)} · {p.status}</p>{p.reviewNote&&<p className="mt-3">Review: {p.reviewNote}</p>}{p.status==='active'&&<a href={'/product/'+p.id} className="underline">View listing</a>}</article>):<p>No products submitted yet.</p>}</div>}
 {tab==='add product'&&<form className={card+' space-y-5'} onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=values(form);void act(async()=>{await marketplaceApi('/seller/products',{...data,price:Number(data.price),ownsRights:true});form.reset();await load();setTab('products');setMessage('Product submitted for review.');});}}><h2 className="text-xl font-bold">Submit a digital product</h2><p>Your paid ZIP stays in your own storage. Use a private MEGA file link, or another source approved by support. This link is never displayed on the listing.</p><div className="grid sm:grid-cols-2 gap-5"><Field name="title" label="Product name" minLength={5}/><Field name="price" label="Price (INR)" type="number" min={1} max={100000} step="0.01"/><label>Category<select name="category" className="block border rounded-lg p-3 w-full mt-2">{SELLER_CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><Field name="version" label="Version"/><Field name="image" label="Public cover image URL" type="url"/><Field name="previewUrl" label="Public live preview URL" type="url"/><Field name="fileSize" label="ZIP size, for example 12 MB"/><Field name="sourceUrl" label="Private paid ZIP source link" type="url" autoComplete="off"/></div><Field name="description" label="Full description" textarea minLength={60}/><Field name="whatsIncluded" label="Included files (one item per line)" textarea minLength={10}/><Field name="requirements" label="Technical requirements (one per line)" textarea minLength={5}/><Field name="license" label="License and permitted uses" textarea minLength={20}/><Field name="support" label="Product support contact and scope" textarea minLength={10}/><Agree name="ownsRights">I have the right to sell every included file, have checked the ZIP for malware and agree to the product policy.</Agree><button className={button} disabled={busy}>Submit for approval</button></form>}
 {tab==='verification'&&<div className={card+' space-y-5'}><h2 className="font-bold text-xl">Identity & bank verification</h2>{!config?.onboardingEnabled&&<p>Verification is temporarily unavailable. Contact support for help with your application.</p>}<p>PAN ending {seller.panLast4} · Bank account ending {seller.bankLast4}</p><p>Document uploads happen in the payment partner’s secure verification portal. Your PAN format alone does not confirm verification. Contact support for identity or bank changes; these require renewed review.</p>{!seller.providerId&&!seller.onboardingStatus&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();const data=values(e.currentTarget);void act(async()=>{await marketplaceApi('/seller/onboard',data);await load();setMessage('Onboarding account created. Open your verification link.');});}}><Field name="password" label="New password for your payment onboarding account (not your store password)" type="password" minLength={12} autoComplete="new-password"/><button className={button} disabled={busy||!config?.onboardingEnabled}>Create verification account</button></form>}{seller.providerId?<button className={button} disabled={busy} onClick={()=>void act(async()=>{const result=await marketplaceApi('/seller/kyc-link',{});window.location.assign(result.url);})}>Open secure verification portal</button>:seller.onboardingStatus&&<p>Your onboarding request is {seller.onboardingStatus}. Support will reconcile the existing request before another is submitted.</p>}</div>}
 {tab==='agreement'&&<div className={card}><p>Accepted by {seller.agreement.signedName} on {new Date(seller.agreement.acceptedAt).toLocaleString()}.</p><p className="text-xs break-all my-3">Agreement record: {seller.agreement.sha256}</p><pre className="whitespace-pre-wrap font-sans text-sm leading-7">{seller.agreement.text}</pre><button className={button+' mt-5'} onClick={()=>{const url=URL.createObjectURL(new Blob([seller.agreement.text+'\nAccepted: '+seller.agreement.acceptedAt+'\nSHA256: '+seller.agreement.sha256],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='seller-agreement.txt';a.click();URL.revokeObjectURL(url);}}>Download agreement</button></div>}
 {tab==='support'&&<div className={card+' space-y-5'}><h2 className="font-bold text-xl">Support & grievances</h2><p>The same team handles support, complaints and appeals. Email <a className="underline" href={'mailto:'+BUSINESS.email}>{BUSINESS.email}</a> with your seller or order reference.</p>{Object.values(seller.cases||{}).map((c:any)=><article key={c.id} className="border-t pt-4"><p className="font-bold">{c.id} · {c.status}</p><p>{c.category} · {c.orderId}</p><p>{c.message}</p>{c.note&&<p>Update: {c.note}</p>}</article>)}</div>}
 </Layout>;
}
export function MarketplaceComplaintsPage(){const [cases,setCases]=useState<any[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const {isAuthenticated,navigate}=useApp();const load=()=>marketplaceApi('/complaints').then(r=>setCases(r.complaints));useEffect(()=>{if(isAuthenticated)void load().catch(e=>setMessage(e.message));},[isAuthenticated]);return <Layout title="Order support & complaints">{message&&<p role="status">{message}</p>}{!isAuthenticated?<button className={button} onClick={()=>navigate('/login')}>Sign in for order support</button>:<><form className={card+' space-y-5'} onSubmit={async e=>{e.preventDefault();const data=values(e.currentTarget);setBusy(true);try{const result=await marketplaceApi('/complaints',data);setMessage('Complaint received: '+result.caseId);await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><Field name="orderId" label="Marketplace order ID"/><label>Issue<select name="category" className="block border rounded-lg p-3 w-full mt-2">{['delivery','refund','fraud','copyright','other'].map(c=><option key={c}>{c}</option>)}</select></label><Field name="message" label="What happened? Include relevant details, but no card numbers, passwords or PAN documents." textarea minLength={20}/><button className={button} disabled={busy}>Submit complaint</button></form>{cases.map(c=><article className={card} key={c.id}><h2 className="font-bold">{c.id} · {c.status}</h2><p>{c.message}</p>{c.note&&<p>{c.note}</p>}</article>)}</>}<p>For existing store products, copyright reports without an order, attachments or appeals, contact <a className="underline" href={'mailto:'+BUSINESS.email}>{BUSINESS.email}</a>. Include your order reference where available.</p></Layout>;}
