import type { Request, Response } from 'express';
// @ts-ignore -- Generated by pnpm build, alongside the main API entrypoint.
import app from '../build/api-app.mjs';
/** Server-render product metadata from the current catalog, including admin additions. */
export default function productPage(req: Request, res: Response) {
  const slug = req.query.slug;
  if (typeof slug !== 'string' || !/^[A-Za-z0-9_-]{1,121}$/.test(slug)) {
    // This branch runs before Express decorates the native Vercel response.
    res.setHeader('X-Robots-Tag', 'noindex');
    res.statusCode = 404;
    res.end('Product not found.');
    return;
  }
  req.url = `/product/${encodeURIComponent(slug)}`;
  app(req, res);
}
